<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>hsrb_wrs_gazebo_launch</name>
  <version>2.0.0</version>
  <description>Launch files for WRS simulator</description>
  <maintainer email="xr-hsr-support@mail.toyota.co.jp">HSR Support</maintainer>

  <license>BSD 3-clause Clear License</license>

  <author>Nobuyuki Matsuno</author>
  <author>Yosuke Matsusaka</author>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>hsrb_gazebo_launch</exec_depend>
  <exec_depend>tmc_wrs_gazebo_launch</exec_depend>
  <exec_depend>tmc_wrs_gazebo_worlds</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
